# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='instrument',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='track',
            name='abc_score',
        ),
        migrations.RemoveField(
            model_name='track',
            name='tempo',
        ),
    ]
