version: '3'
services:
  api:
    build: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - ./api:/code
    links:
    - db
    - redis

  fe:
    build: fe
    volumes:
    - ./fe:/usr/share/nginx/html/
    # command: nginx -g 'daemon off;'
    command: bash -c "npm rebuild node-sass && npm start"
    ports:
    - 80:3000
    links:
    - api

  redis:
    image: redis

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: